// This file is auto-generated by scripts/generate-default-photos.mjs
// It lists all example images under public/photos/ (used for the “使用示例” feature).

export const DEFAULT_PHOTO_FILES = [
  "1.jpg",
  "2.jpg",
  "3.jpg"
] as const;
